apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg.cluster.yaml
  - valkey.yaml
  - config.yaml
  - deployment.yaml
  - http-svc.yaml
  - init.yaml
  - pvc.yaml
  - ssh-svc.yaml
  - ingress.yaml
